version: "2"

linters:
  default: all
  disable:
    - testpackage
    - forbidigo
    - paralleltest
    - varnamelen
    - exhaustruct
    - wrapcheck
    - ireturn
    - cyclop
    - funlen
    - gocognit
    - maintidx
    - gochecknoinits
    - depguard

formatters:
  settings:
    lll:
      line-length: 180
