# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: {{ .appName }}
before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  ldflags:
  - -s -w -X cmd.version={{`{{.Version}}`}}
release:
  prerelease: auto
nfpms:
- file_name_template: '{{`{{ .ProjectName }}`}}_{{`{{ .Arch }}`}}'
  maintainer: {{ .maintainerName }} <{{ .maintainerEmail }}>
  homepage: {{ .maintainerUrl }}
  description: >-
    {{ .appDescription }}
  license: MIT
  formats:
  - deb
  - rpm
  - apk
  bindir: /usr/bin
  section: utils
  contents:
  - src: ./LICENSE
    dst: /usr/share/doc/nfpm/copyright
    file_info:
      mode: 0644
sboms:
- artifacts: archive
{{ $githubUserOrg := trimPrefix "https://github.com/" .githubRepo | splitList "/" | first }}
brews:
- repository:
    owner: {{ $githubUserOrg }}
    name: homebrew-{{ .appName }}
    branch: main
    token: "{{`{{ .Env.SKA_HOMEBREW_TOKEN }}`}}"
  # yamllint disable-line rule:comments rule:line-length
  url_template: https://github.com/<user>/<repo>/releases/download/{{`{{ .Tag }}`}}/{{`{{ .ArtifactName }}`}}
  commit_author:
    name: {{ .maintainerName }}
    email: {{ .maintainerEmail }}
  directory: Formula
  homepage: {{ .githubRepo}}
  description: >-
    {{ .appDescription }}
  license: MIT
archives:
- wrap_in_directory: true
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{`{{ .Tag }}`}}-next'
changelog:
  disable: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^*.md:'