# ska-start:centrally-managed
coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%
# ska-end
ignore:
  - "cmd/man.go"