name: golangci-lint
on:
  push:
    paths:
      - '**.go'
    branches:
      - master
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

{{- if eq .buildFramework "MISE"}}
      - name: Install mise and tools
        uses: jdx/mise-action@v2

      - name: Lint
        run: mise run lint
{{- else}}
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0

      - name: Lint
        run: make lint
{{- end}}
